language: python
sudo: false
python:
  - "2.7"
install:
  - travis_retry pip install -q mock nose PyHamcrest
  - travis_retry pip install behave
 - travis_retry pip install selenium

script:
  - python --version
  - behave --junit
 
