language: python
sudo: false
python:
  - "2.7"
install:
  - travis_retry pip install -q mock nose PyHamcrest
  - travis_retry pip install behave
 

script:
  - python --version
  - behave -f progress --junit features/
 
